### PR TITLE
♻️  Refactor UPath

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by Koncopd** [comment]
I don't think subclassing like you want here will really work due to this https://github.com/fsspec/universal_pathlib/blob/befb71ea1e1a8c3685ddea3828c99cfe172257a3/upath/core.py#L162

I did this ugly extending of upath exactly due to this `__new__` overwrite in `upath`.

**Comment by Koncopd** [comment]
Can explain the problem in details in a call.

**Comment by falexwolf** [comment]
Hm, so far things seem to work. A `__new__` shouldn't prevent subclassing. I've subclassed classes with `__new__` many times before. 🤔 
image

**Comment by falexwolf** [comment]
Well, in any case, in making `UPath` a user-facing first-class citizen I'd like to thoroughly clean up documentation and understand the underlying logic. I'll play around with things a bit more.

If you're still available for a call, happy to call, of course!

**Comment by falexwolf** [comment]
OK, I see that things seem to get a bit complicated...

**Comment by falexwolf** [comment]
Fun:
image

(Because __new__ returns an S3Path, which is no longer a subclass of the LaminUPath then. Hm)

**Comment by falexwolf** [comment]
Going roughly back to what you had, @Koncopd, just that it seems I was able to fix the docs somehow through fixing a few docstrings.

The whole class didn't display correctly before.

**Comment by Koncopd** [comment]
> Fun: image
> 
> (Because **new** returns an S3Path, which is no longer a subclass of the LaminUPath then. Hm)

Yes, exactly, this is the problem here with the logic of `UPath.__new__`.

**Pull request merged**
