### PR TITLE
🚸 Add delete confirmation dialogue

### PR DESCRIPTION
**Pull request by Zethson**
Fixes https://github.com/laminlabs/lamindb-setup/issues/295

### CODE REVIEW

**Comment by Zethson** [comment]
> ImportError: cannot import name 'ParentsAware' from 'lnschema_core.models' (/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/lnschema_core/models.py)

Not sure where this is coming from now

**Comment by falexwolf** [comment]
Thank you, @Zethson, this is great!

**Comment by falexwolf** [comment]
I think tests fail because of an inconsistency between lnschema-core submodule and lnschema-bionty install. I think I should meanwhile remove the lnschema-core submodule or find another way that this can't happen anymore

**Comment by falexwolf** [comment]
No, I see it's not that. Hmmm.

**Comment by falexwolf** [comment]
Let's see if this some flakiness here - I haven't encountered any for a good while

**Comment by Zethson** [comment]
I assume there's a lamin delete that expects an answer aka a "yes" somewhere that I missed? Currently afk

**Comment by falexwolf** [comment]
Oh, right. That's very likely the reason. Would you search for it? This is otherwise good to merge from my point of view!

**Pull request merged**
