### PR TITLE
🎨 Move default storages to folders

### PR DESCRIPTION
**Pull request by falexwolf**
https://laminlabs.slack.com/archives/C04TMJPNCBS/p1706266454001749

### CODE REVIEW

**Comment by falexwolf** [comment]
@Koncopd, is there anything about the locker that assumes it's at the root of a bucket? Shouldn't it just work as well if the root is a folder within a bucket?

**Comment by Koncopd** [comment]
Hm, it should work, yes.

**Comment by falexwolf** [comment]
I'll merge this for now, because it blocks a sequence of things that I have to do to get the storage service up and running.

If there is a bug with the locker, we can fix it in another PR.

**Comment by Koncopd** [comment]
I would rather prefer to figure out first what is the problem.

**Comment by Koncopd** [comment]
I am checking now what is the problem here

**Comment by Koncopd** [comment]
Ok, it looks like i have found the problem.

**Comment by Koncopd** [comment]
In this notebook https://github.com/laminlabs/lamindb-setup/blob/folders/docs/prod-only/test-load-lock.ipynb
`root = UPath("s3://lamindb-ci/test-load-lock/", cache_regions=True)`
`exclusion = root / ".lamindb/_exclusion/"`
produced root `"s3://lamindb-ci/test-load-lock**//**.lamindb/_exclusion/"`
So the trailing slash in UPath is ab big problem actually, it results in double slash on `/` operator.

**Comment by Koncopd** [comment]
Actually, i think it is a `UPath` bug, i will report it.

**Comment by falexwolf** [comment]
Maybe it's fixed and we just need to upgrade upath?

**Comment by falexwolf** [comment]
To get the tests entirely to work, I need to re-deploy a schema change in the hub, and then post-populate something. Because these changes are needed for anything else, I'll now merge them in this broken state to main.

**Comment by Koncopd** [comment]
Maybe it is fixed indeed, i will check.

**Pull request merged**
