### PR TITLE
♻️ Check manual credentials in path.fs, actually reuse anon

### PR DESCRIPTION
**Pull request by Koncopd**
subj

### CODE REVIEW

**Comment by Koncopd** [comment]
@falexwolf is hosted init broken again?

**Comment by falexwolf** [comment]
Something seems off, yes. I haven't debugged it yet.

**Comment by falexwolf** [comment]
It started to appear all of a sudden, I need to check this.

**Comment by Koncopd** [comment]
It seems to be on the side of hub. Also the same test on `build / prod-staging (staging)` passes.

**Comment by falexwolf** [comment]
Yes, so, this is the reason for why hosted storage was broken: https://laminlabs.slack.com/archives/C04TMJPNCBS/p1707171896355059

**Pull request merged**
