### PR TITLE
✨ Compute hash for files in Google Cloud Storage and Hugging Face

### PR DESCRIPTION
**Pull request by Koncopd**
Closes https://github.com/laminlabs/lamindb-setup/issues/748

### CODE REVIEW

**Comment by falexwolf** [comment]
Darn, I think we only have code find files via blob hash: https://github.com/laminlabs/lamindb/blob/5c90903debbb6b35b2e00fc6f1be2a6e82ebe629/lamindb/core/_sync_git.py#L56

It should be rather straightforward, however, to get the blob hash.

As you say the commit hash is no valid proxy and indeed dangerous.

**Comment by Koncopd** [comment]
Also not given by `stat`.

image

I am disabling hashing for huggingface paths for now.

**Comment by falexwolf** [comment]
I believe hashes are very important and I'd not disable it.

If there is no way to get the full hash you can compute a pseudo hash like retro does by hashing the size and the file path.

**Comment by Koncopd** [comment]
Yes, but this is a different approach than we have now, i would not do it just for huggingface and leave for as we have now for everything else.
I agree that hashing is important, and here i enable it for files in google cloud. For huggingface it is certainly safer also to have no hashing rather than commit hashing.

**Comment by falexwolf** [comment]
The pseudo hash will be good enough for many purposes because these hugging face datasets will rarely be renamed.

Of course there are also a wide range of cases in which only the size is a good hash candidate but then there are cases where one deals with many images etc. of the exact same size and one needs another ingredient.

If there is a micro-second resolved created_at timestamp that's invariant under renaming on huggingface that'd be the perfect candidate for combination with the size to form a good pseudo hash.

**Comment by falexwolf** [comment]
> Yes, but this is a different approach than we have now, i would not do it just for huggingface and leave for as we have now for everything else.

We're already working with different hash types and code the type of the hash in `_hash_type`. Hence, I don't see an issue to use a pseudo hash just for hugging face.

The big danger is that idempotency is lost and people might duplicate ingestion of hugging face datasets which will lead to problems.

**Comment by Koncopd** [comment]
As you see, there is also no timestamp on file level, only commit level.

**Comment by falexwolf** [comment]
Oh, but there is a `blob_id` which is the blob hash! Sorry for not spotting this earlier. You can simply use it, I'm pretty sure of that.

**Comment by falexwolf** [comment]
If the blob_id is 40char it's the SHA1 that we also compute in lamindb-setup here: https://github.com/laminlabs/lamindb-setup/blob/2e905fdb8977b2ca232b9324cad4205b9253c671/lamindb_setup/core/hashing.py#L60

You can also do a simple comparison for a small file and you'll likely find it's the same thing.

**Comment by falexwolf** [comment]
You should re-encode the hex code to base64 and truncate to 22 char because that's the limit for the hash field.

Along the lines of this: https://github.com/laminlabs/lamindb-setup/blob/2e905fdb8977b2ca232b9324cad4205b9253c671/lamindb_setup/core/hashing.py#L92

**Comment by Koncopd** [comment]
Yep, undersood.

**Pull request merged**
