### PR TITLE
✨ Add submodule for entry point functionality

### PR DESCRIPTION
**Pull request by ap--**
Hello Lamins,

This PR adds an `_entry_points` submodule with a `call_registered_entry_points` function, which can then be used in `lamindb` as well as `lamin-cli` to provide a hook that other packages can use to do additional setup that might be required for lamindb to function correctly within their custom infrastructure.

usage example xref: laminlabs/lamin-cli#68

Cheers,
Andreas 😃

### CODE REVIEW

**Comment by falexwolf** [comment]
Thanks, Andreas! I'll fix the CI runs.

What test shall we add for this?

**Comment by ap--** [comment]
Good question, since the test will at the end rely on lamindb, lamin-cli and lamindb-setup it would be great if you could advise where I should add tests ideally.

In every dependency? or only in lamindb?

**Comment by falexwolf** [comment]
I get how it works for CLI calls. 

```
call_registered_entry_points("lamin-cli.setup", module_globals=globals())
```

I'll read up in the original issue for how it would be called for lamindb.

Would you want this to be automatically called upon importing lamindb?

**Comment by falexwolf** [comment]
Regarding the general layout, I'm responding in the original issue.

**Comment by falexwolf** [comment]
Ok, tests fail because the secrets aren't passed on because you made your PR from a fork and there doesn't seem to be a setting to enable it:

image

I'll make you a collaborator with write access, then you don't need to make forks anymore.

**Comment by ap--** [comment]
perfect. I'll add tests and will reopen from a branch in laminlabs/lamindb-setup

**Pull request closed without merging**
