### PR TITLE
🔥 Adapt locker to lock entire lamindb session

### PR DESCRIPTION
**Pull request by Koncopd**
Now 
`settings.instance.cloud_sqlite_locker.lock()` doesn't lock anything by itself, it just check if it can obtain write access to the (cloud sqlite) instance.
After calling `settings.instance.cloud_sqlite_locker.lock()` at the load of an instance (internally), all write operations in lamindb should check the property `settings.instance.cloud_sqlite_locker.has_lock` before proceeding. 

upd:
Now prevents an instance from loading completely if locked by another user.

### CODE REVIEW

**Comment by Koncopd** [comment]
@falexwolf We have `unlock` in `_update_cloud_sqlite_file` but it is called not only by `close` but also by `setup_django`, so it is probably incorrect.

**Comment by falexwolf** [comment]
It is correct!

**Comment by falexwolf** [comment]
Does the comment I put not make sense? Happy to do a brief call!
https://github.com/laminlabs/lamindb-setup/blob/696e6f0bb853bf5de1280c6d69c617a77f5bd61a/lamindb_setup/dev/_django.py#L67-L68

**Comment by falexwolf** [comment]
Deploy migration command means: `lamin migrate deploy`. This is an isolated admin command that

**Pull request merged**
