### PR TITLE
♻️ Refactor to use UPath everywhere

### PR DESCRIPTION
**Pull request by Koncopd**
heh, accidently named the branch "umap_refactor"...

### CODE REVIEW

**Comment by falexwolf** [comment]
Yeah, fun branch name! :D

**Comment by falexwolf** [comment]
When completing this, could you also rename `_storage.py` to `_settings_storage.py`, so that it's consistently named with the other settings modules?

**Comment by Koncopd** [comment]
@falexwolf you can rename, i think i will need to redo this anyways.

**Comment by falexwolf** [comment]
Confirming: Are you really sure you're willing to lose all this work that went into this already? Or didn't you spend a lot of time here?

**Comment by falexwolf** [comment]
Ok then!

**Comment by falexwolf** [comment]
Thinking more: Could you maybe do it while you'll work on this code anyway? It might take me a while to get things to work (even though I think it's a simple rename).

**Comment by Koncopd** [comment]
yep

**Pull request closed without merging**
