### PR TITLE
♻️ Rename and set empty locker for now

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by Koncopd** [comment]
There is an import from `_exclusion` in `__init__.py` also, maybe in other places too, so should be renamed there also.

**Comment by falexwolf** [comment]
Nice, GitHub seems down here:
image

**Comment by falexwolf** [comment]
Even github itself shows it correctly, but doesn't trigger the action here:
image

**Comment by falexwolf** [comment]
That's crazy, I merged this one now, but it didn't take the last commit into account despite it being on the remote `amend` branch...

**Comment by falexwolf** [comment]
Making a new PR: https://github.com/laminlabs/lamindb-setup/pull/404

**Pull request merged**
