### PR TITLE
🚸 Implement delimiter validation during `init` and `delete`

### PR DESCRIPTION
**Pull request by bpenteado**

### CODE REVIEW

**Comment by falexwolf** [comment]
Thanks, Bernardo! This is great! 

Just: Please add two tests that trigger these two errors.

6 months ago, I've learned this idiom from you:
```
with pytest.raises(Exception) as error:
    ln.save(files)
print(error.exconly())
```

Today, if you'd go through the lamindb unit tests, you'd see tests for the error messages all over the place! They all look like this:
```
with pytest.raises(Exception) as error:
    ln.save(files)
assert error.exconly() == "target error message"
```

So, I'm asking you to also do it like this here!

**Comment by bpenteado** [comment]
> 

Done!

**Comment by bpenteado** [comment]
> Thanks, Bernardo! This is great!
> 
> Just: Please add two tests that trigger these two errors.
> 
> 6 months ago, I've learned this idiom from you (it's still used here: https://lamin.ai/docs/faq/acid):
> 
> ```
> with pytest.raises(Exception) as error:
>     ln.save(files)
> print(error.exconly())
> ```
> 
> Today, if you'd go through the lamindb unit tests, you'd see tests for the error messages all over the place! They all look like this:
> 
> ```
> with pytest.raises(Exception) as error:
>     ln.save(files)
> assert error.exconly() == "target error message"
> ```
> 
> So, I'm asking you to also do it like this here!

Done!

**Comment by falexwolf** [comment]
Thanks, Bernardo! Good to merge!

**Pull request merged**
